# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build and deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # 安装node
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    
    # 迁出代码
    - uses: actions/checkout@master

    # 安装依赖并打包
    - name: Run install & build script
      run: npm install && npm run build

    # 上传到服务器
    - name: Deploy to Server
      uses: SamKirkland/FTP-Deploy-Action@3.1.0
      with:
        ftp-server: ftp://47.105.126.118/
        ftp-username: ftp
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist
